/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    BadgeIcon: typeof import('./src/components/IconCom/BadgeIcon.vue')['default']
    HomeIcon: typeof import('./src/components/IconCom/HomeIcon.vue')['default']
    LoginOutIcon: typeof import('./src/components/IconCom/LoginOutIcon.vue')['default']
    Menu: typeof import('./src/components/com/Menu.vue')['default']
    MenuT: typeof import('./src/components/com/MenuT.vue')['default']
    NavHeader: typeof import('./src/components/com/NavHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoiceIcon: typeof import('./src/components/IconCom/VoiceIcon.vue')['default']
  }
}
